version: '3.9'

services:
  ghcrtest:
    image: ghcr.io/yanorei32/ghcr-test:latest@sha256:a208935bb4eb2892016a37ffca068375d85b7bb04963009e0a9aacb4dc8aca1e
    hostname: ghcrtest
    container_name: ghcrtest__ghcrtest
    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 64m

    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m

    network_mode: none
